language: node_js
node_js:
  - "10"
install:
  - yarn install
cache:
  directories:
    - node_modules
script:
  - yarn build:app
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  on:
    branch: master
